### ISSUE TITLE
Update for django-esi 2.0.0

### ISSUE THREAD

**Issue by ppfeufer** [pvyParts/allianceauth-mumble-temp#6]
Just pulled in my test system your `corpstats-two` from master to check the newest features, which also requires `django-esi` 2.0.0 and got the message that `allianceauth-mumbletemps` does not.

```
allianceauth-mumbletemps 2.0.0 has requirement django-esi<2.0,>=1.6.0, but you'll have django-esi 2.0.0 which is incompatible.
```
A quick test showed no issues so far and `mumbletemp` seems to be working with `django-esi` 2.0.0 so far.

**Comment by pvyParts** [comment]
Yeah I have had this running with django-esi 2.0 for ages.

I'll remove the tag in setup.
